/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ProductoDAO;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

public class VentanaStock extends javax.swing.JFrame {
    /**
     * Creates new form VentanaStock
     */

    public VentanaStock() {
        initComponents();
    }
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonEliminar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();
        buttonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Tipo Producto", "Sub TIpo Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMostrar);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Inventario");

        buttonEliminar.setText("ELIMINAR");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonModificar.setText("MODIFICAR");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonVolver.setText("VOLVER");
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        buttonBuscar.setText("BUSCAR");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonAgregar.setText("AGREGAR");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(buttonAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAgregar)
                        .addGap(24, 24, 24)
                        .addComponent(buttonBuscar)
                        .addGap(24, 24, 24)
                        .addComponent(buttonModificar)
                        .addGap(24, 24, 24)
                        .addComponent(buttonEliminar)
                        .addGap(24, 24, 24)
                        .addComponent(buttonVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTabla()
   {
       DefaultTableModel dtm=(DefaultTableModel)tblMostrar.getModel();
       int n=tblMostrar.getRowCount()-1;
       for (int i = 0; i <=n; i++) {
           dtm.removeRow(dtm.getRowCount()-1);
       }
   }
    
    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        DefaultTableModel dtm =(DefaultTableModel)tblMostrar.getModel();
        int fila = tblMostrar.getSelectedRow();
        if(fila == -1){
        JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        }
        else
        {
            String aux = JOptionPane.showInputDialog("Escriba: ELIMINAR para confirmar la eliminación del producto");
            if(aux == "ELIMINAR"){
            String id = String.valueOf(tblMostrar.getValueAt(fila, 0));
            ProductoDAO productoDAO=new ProductoDAO();
            productoDAO.eliminarProducto(id);
            JOptionPane.showMessageDialog(this,"Producto Eliminado");
            dtm.removeRow(fila);
            }
            else{
                JOptionPane.showMessageDialog(this,"Palabra incorrecta. El producto no ha sido eliminado");
            }
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)tblMostrar.getModel();
        int fila = tblMostrar.getSelectedRow();
        if(fila == -1){
        JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
        }else{
            String id = String.valueOf(tblMostrar.getValueAt(fila, 0));
            String nombre = String.valueOf(tblMostrar.getValueAt(fila, 1));
            String tipoProducto = String.valueOf(tblMostrar.getValueAt(fila, 3));
            String subTipoProducto = String.valueOf(tblMostrar.getValueAt(fila, 3));
            int precio = Integer.parseInt(valueOf(tblMostrar.getValueAt(fila, 4)));
            
            Producto producto = new Producto(id, nombre, tipoProducto, subTipoProducto, precio);
            ProductoDAO productoDAO=new ProductoDAO();
            productoDAO.modificarProducto(producto);
            JOptionPane.showMessageDialog(this, "Producto modificado");
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        dispose();
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        limpiarTabla();
        ProductoDAO productoDAO = new ProductoDAO();
        String productoABuscar = JOptionPane.showInputDialog("Ingrese codigo del producto a buscar");
        Producto producto = productoDAO.buscarProducto(productoABuscar);

        if(producto == null)//No existe
        {
            ArrayList <Producto> productoList = productoDAO.obtenerTodo();
            if(productoList.size() == 0){
                JOptionPane.showMessageDialog(this, "No hay Productos en bodega");
            }else{
                DefaultTableModel dtm = (DefaultTableModel)tblMostrar.getModel();
                String [][] datos = new String[productoList.size()][5];
                for (int i = 0; i < productoList.size(); i++) {
                    datos[i][0] = productoList.get(i).getId();
                    datos[i][1] = productoList.get(i).getNombre();
                    datos[i][2] = productoList.get(i).getTipoProducto();
                    datos[i][3] = productoList.get(i).getSubTipoProducto();
                    datos[i][4] = String.valueOf(productoList.get(i).getPrecio());                
                    dtm.addRow(datos[i]);
                }
                tblMostrar.setModel(dtm);
            }
        }
        else //Existe
        {
            DefaultTableModel dtm = (DefaultTableModel)tblMostrar.getModel();
            String [] datos = new String[5];
            datos[0] = producto.getId();
            datos[1] = producto.getNombre();
            datos[2] = producto.getTipoProducto();
            datos[3] = producto.getSubTipoProducto();
            datos[4] = String.valueOf(producto.getPrecio());
            dtm.addRow(datos);
            tblMostrar.setModel(dtm);
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        VentanaAgregar ven= new VentanaAgregar();
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        ven.setTitle("Stock");
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); 
    }//GEN-LAST:event_buttonAgregarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMostrar;
    // End of variables declaration//GEN-END:variables
}
